version: "3"
services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    depends_on:
      - api
      - client
    restart: always
    image: tiwari123/3-tier-nginx:v1.${IMAGE_TAG}
    ports:
      - "3050:80"

  api:
    image: tiwari123/3-tier-backend:v1.${IMAGE_TAG}
    environment:
      - PGUSER=${PGUSER}
      - PGHOST=${PGHOST}
      - PGDATABASE=${PGDATABASE}
      - PGPASSWORD=${PGPASSWORD}
      - PGPORT=${PGPORT}

  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    image: tiwari123/3-tier-frontend:v1.${IMAGE_TAG}

volumes:
  postgres_data:
