name: Docker CI and EC2 CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  docker_build_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          cd client && sh frontend_build.sh ${{ github.run_number }}
          cd ../server && sh backend_build.sh ${{ github.run_number }}
          cd ../nginx  && sh nginx.sh ${{ github.run_number }}

  ec2-cd:
    runs-on: ubuntu-latest
    needs: docker_build_push
    steps:
      - name: SSH into EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd Mrikal-cicd-assignment
            sudo IMAGE_TAG=${{ github.run_number }} docker-compose --env-file .env up -d
